configMaps:
  alllogs.conf: |-
    <source>
      @id fluentd-argo-all-logs.log
      @type tail
      path /var/log/containers/*svls*.log,/var/log/containers/*argo-deploy*.log,/var/log/containers/*argo-build*.log
      pos_file /var/log/fluentd-all-logs.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag raw.kinto.alllogs.*
      read_from_head true
      format json
    </source>

    <filter kinto.alllogs.**>
      @type record_transformer
      enable_ruby true
      <record>
        target_index all-logs-${time.strftime("%Y.%m.%d")}
      </record>
    </filter>
